services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    command: start
    # optional: uncomment to run as your host UID
    # user: "${UID}:${GID}"
    

volumes:
  n8n_data:

